name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PWD_SSH_KEY }}

      - name: Upload docker-compose.yml
        run: |
          scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/webapi/docker-compose.yml

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/webapi &&
            docker compose pull &&
            docker compose up -d --build --remove-orphans
          "
