name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PWD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Create folder on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
          ip172-18-0-25-d3btih0l2o9000egd8m0@direct.labs.play-with-docker.com \
          "mkdir -p ~/web_api && echo 'CREATED' && ls -ld ~/web_api"