name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PWD_SSH_KEY }}

      - name: Prepare server folder
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            mkdir -p ~/web_api
            if [ ! -f ~/web_api/docker-compose.yml ]; then
              echo "" > ~/web_api/docker-compose.yml
            fi
          EOF
      - name: Copy docker-compose.yml to VPS
        run: |
          scp -o StrictHostKeyChecking=no WebApi/docker-compose.yml \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/web_api/docker-compose.yml

      - name: Deploy to VPS
        run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
         cd ~/web_api
         docker pull ${{ secrets.DOCKERHUB_USERNAME }}/web_api:latest
         docker compose up -d
         docker image prune -f
         "
         EOF
