name: CD Pipeline

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:
  docker:    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: WebApi/Dockerfile
          push: true
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web_api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web_api:${{ github.sha }}
      
    